# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "13:00"
      timezone: Europe/Sofia
      day: "monday"
    labels:
      - "ActionsUpdate"
    reviewers:
      - "owolp"
    target-branch: "develop"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
      timezone: Europe/Sofia
      labels:
        - "DependencyUpdate"
      reviewers:
        - "owolp"
      target-branch: "develop"
