[versions]
ktlint = "0.42.1"
kotlin = "1.5.30"

[libraries]

# AndroidX
android-build-gradle = "com.android.tools.build:gradle:7.1.2"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-costraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
google-material = "com.google.android.material:material:1.5.0"
jetbrains-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
junit = "junit:junit:4.13"
