[versions]
dagger = "2.41"
jvmTarget = "11"
ktlint = "0.42.1"
kotlin = "1.6.10"

[libraries]
android-build-gradle = "com.android.tools.build:gradle:7.1.2"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-costraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidx-startup = "androidx.startup:startup-runtime:1.1.1"
google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
google-dagger-hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
google-material = "com.google.android.material:material:1.5.0"
jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
jetbrains-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0"
junit = "junit:junit:4.13.2"
