[versions]
accompanist = "0.25.1"
agconnect = "1.7.3.300"
androidJunit = "1.3.0"
compose = "1.3.0-rc01"
composeMaterial3 = "1.0.0-beta03"
composeCompiler = "1.3.1"
coroutines = "1.6.4"
dagger = "2.44"
junit = "5.9.1"
jvmTarget = "11"
lifecycle = "2.6.0-alpha02"
kotlin = "1.7.10"
navigation = "2.5.2"
room = "2.4.3"
test = "1.4.0"

[libraries]
acra-http = "ch.acra:acra-http:5.9.6"
airbnb-android-lottie-compose = "com.airbnb.android:lottie-compose:5.2.0"
android-build-gradle = "com.android.tools.build:gradle:7.3.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.6.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.0-rc01"
androidx-arch-core-testing = "androidx.arch.core:core-testing:2.1.0"
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
androidx-compose-material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "composeMaterial3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-core-splash = "androidx.core:core-splashscreen:1.0.0"
androidx-costraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.0.1"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-security-crypto = "androidx.security:security-crypto:1.0.0"
androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test" }
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "test" }
cash-turbine = "app.cash.turbine:turbine:0.11.0"
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
google-dagger-hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
google-firebase-bom = "com.google.firebase:firebase-bom:30.5.0"
google-firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:2.9.2"
google-firebase-performance-gradle = "com.google.firebase:perf-plugin:1.4.1"
google-material = "com.google.android.material:material:1.6.1"
google-gms-services = "com.google.gms:google-services:4.3.14"
google-truth = "com.google.truth:truth:1.1.3"
huawei-agconnect-agcp = { module = "com.huawei.agconnect:agcp", version.ref = "agconnect" }
huawei-agconnect-apms = "com.huawei.agconnect:agconnect-apms:1.6.1.303"
huawei-agconnect-core = { module = "com.huawei.agconnect:agconnect-core", version.ref = "agconnect" }
huawei-agconnect-crash = { module = "com.huawei.agconnect:agconnect-crash", version.ref = "agconnect" }
huawei-agconnect-remoteconfig = { module = "com.huawei.agconnect:agconnect-remoteconfig", version.ref = "agconnect" }
huawei-hms-hianalytics = "com.huawei.hms:hianalytics:6.8.0.300"
mannodermaus-gradle-plugins-android-junit5 = "de.mannodermaus.gradle.plugins:android-junit5:1.8.2.1"
mannodermaus-junit5-android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "androidJunit" }
mannodermaus-junit5-android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "androidJunit" }
jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
jetbrains-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
jetbrains-kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
mockk-mockk = "io.mockk:mockk:1.13.1"
squareup-leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.9.1"
zetetic-sqlcipher = "net.zetetic:android-database-sqlcipher:4.5.2"