[versions]
agconnect = "1.6.6.200"
androidJunit = "1.3.0"
coroutines = "1.6.2"
dagger = "2.42"
junit = "5.8.2"
jvmTarget = "11"
lifecycle = "2.5.0-rc01"
ktlint = "0.42.1"
kotlin = "1.7.0"
room = "2.4.2"
test = "1.4.0"

[libraries]
acra-http = "ch.acra:acra-http:5.9.3"
android-build-gradle = "com.android.tools.build:gradle:7.2.1"
androidx-activity-ktx = "androidx.activity:activity-ktx:1.4.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-arch-core-testing = "androidx.arch.core:core-testing:2.1.0"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-core-splash = "androidx.core:core-splashscreen:1.0.0-rc01"
androidx-costraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-security-crypto = "androidx.security:security-crypto:1.0.0"
androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test" }
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "test" }
cash-turbine = "app.cash.turbine:turbine:0.8.0"
google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
google-dagger-hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
google-firebase-bom = "com.google.firebase:firebase-bom:30.1.0"
google-firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:2.9.0"
google-firebase-performance-gradle = "com.google.firebase:perf-plugin:1.4.1"
google-material = "com.google.android.material:material:1.6.1"
google-gms-services = "com.google.gms:google-services:4.3.10"
google-truth = "com.google.truth:truth:1.1.3"
huawei-agconnect-agcp = { module = "com.huawei.agconnect:agcp", version.ref = "agconnect" }
huawei-agconnect-apms = "com.huawei.agconnect:agconnect-apms:1.5.2.310"
huawei-agconnect-core = { module = "com.huawei.agconnect:agconnect-core", version.ref = "agconnect" }
huawei-agconnect-crash = { module = "com.huawei.agconnect:agconnect-crash", version.ref = "agconnect" }
huawei-agconnect-remoteconfig = { module = "com.huawei.agconnect:agconnect-remoteconfig", version.ref = "agconnect" }
huawei-hms-hianalytics = "com.huawei.hms:hianalytics:6.5.0.300"
mannodermaus-gradle-plugins-android-junit5 = "de.mannodermaus.gradle.plugins:android-junit5:1.8.2.0"
mannodermaus-junit5-android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "androidJunit" }
mannodermaus-junit5-android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "androidJunit" }
jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
jetbrains-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
jetbrains-kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
mockk-mockk = "io.mockk:mockk:1.12.4"
squareup-leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.9.1"
zetetic-sqlcipher = "net.zetetic:android-database-sqlcipher:4.5.1"