opt_out_usage

# This file contains the fastlane.tools configuration
# You can find the documentation at https: //docs.fastlane.tools
  #
# For a list of all available actions, check out
#
# https: //docs.fastlane.tools/actions
  #
# For a list of all available plugins, check out
#
# https: //docs.fastlane.tools/plugins/available-plugins
  #

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Assemble Dev Release"
  lane :assemble_dev_release do
    build_android_app(
      task: "assemble",
      flavor: "dev",
      build_type: "release"
    )
  end

  desc "Assemble Play Release"
  lane :assemble_play_release do
    build_android_app(
      task: "assemble",
      flavor: "play",
      build_type: "release"
    )
  end

  desc "Assemble Gallery Release"
  lane :assemble_gallery_release do
    build_android_app(
      task: "assemble",
      flavor: "gallery",
      build_type: "release"
    )
  end

  desc "Assemble FOSS Release"
  lane :assemble_foss_release do
    build_android_app(
      task: "assemble",
      flavor: "foss",
      build_type: "release"
    )
  end

  desc "Runs Ktlint"
  lane :ktlint do
    gradle(task: "ktlintCheck")
  end

  desc "Runs Detekt"
  lane :detekt do
    gradle(task: "detektCheck")
  end

  desc "Runs Dev unit tests"
  lane :dev_debug_unit_tests do
    gradle(task: "testDevDebugUnitTest")
  end

  desc "Runs Kover"
  lane :kover do
    gradle(task: "koverXmlReportDevDebug")
  end

  desc "Runs Dokka"
  lane :dokka do
    gradle(task: "dokkaHtmlMultiModule")
  end

  desc "Submit new Dev build to Firebase App Distribution"
  lane :distribute_dev do |options|

    build_android_app(
        task: "assemble",
        flavor: "dev",
        build_type: "release"
    )

    firebase_app_distribution(
        app: options[:appId],
        groups: options[:group],
        firebase_cli_token: options[:firebaseToken]
    )
  end

  desc "Submit new Play build to Firebase App Distribution"
  lane :distribute_play do |options|

    build_android_app(
        task: "assemble",
        flavor: "play",
        build_type: "release"
    )

    firebase_app_distribution(
        app: options[:appId],
        groups: options[:group],
        firebase_cli_token: options[:firebaseToken]
    )
  end

  desc "Submit new Gallery build to Firebase App Distribution"
  lane :distribute_gallery do |options|

    build_android_app(
        task: "assemble",
        flavor: "gallery",
        build_type: "release"
    )

    firebase_app_distribution(
        app: options[:appId],
        groups: options[:group],
        firebase_cli_token: options[:firebaseToken]
    )
  end

  desc "Submit new FOSS build to Firebase App Distribution"
  lane :distribute_foss do |options|

    build_android_app(
        task: "assemble",
        flavor: "foss",
        build_type: "release"
    )

    firebase_app_distribution(
        app: options[:appId],
        groups: options[:group],
        firebase_cli_token: options[:firebaseToken]
    )
  end
end
