name: assemble

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  assemble_dev:
    name: Assemble Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Restore Dev Secrets
        run: |
          echo "dev_signing_key_alias=${{ secrets.DEV_SIGNING_KEY_ALIAS }}" >> secrets.properties
          echo "dev_signing_key_password=${{ secrets.DEV_SIGNING_KEY_PASSWORD }}" >> secrets.properties
          echo "dev_signing_keystore_password=${{ secrets.DEV_SIGNING_KEYSTORE_PASSWORD }}" >> secrets.properties
          echo "${{ secrets.DEV_KEYSTORE }}" > dev.keystore.asc
          gpg --batch --decrypt --output "config/keystore/dev.keystore" --passphrase "${{ secrets.DEV_SIGNING_KEYSTORE_GPG }}" --yes "dev.keystore.asc"

      - name: Run Fastlane Assemble Dev Release Lane
        run: fastlane assemble_dev_release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: dev_app_apk
          path: "*/build/outputs/apk/*/release/*.apk"

  assemble_play:
    name: Assemble Play
    runs-on: ubuntu-latest
    #    if: ${{ github.workflow_run.conclusion == 'success' }} && ${{ github.event_name == 'push' }} && (${{ github.ref_name == 'develop' }} || ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'release' }})

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Restore Prod Secrets
        run: |
          echo "prod_signing_key_alias=${{ secrets.PROD_SIGNING_KEY_ALIAS }}" >> secrets.properties
          echo "prod_signing_key_password=${{ secrets.PROD_SIGNING_KEY_PASSWORD }}" >> secrets.properties
          echo "prod_signing_keystore_password=${{ secrets.PROD_SIGNING_KEYSTORE_PASSWORD }}" >> secrets.properties
          echo "${{ secrets.PROD_KEYSTORE }}" > prod.keystore.asc
          gpg --batch --decrypt --output "config/keystore/prod.keystore" --passphrase "${{ secrets.PROD_SIGNING_KEYSTORE_GPG }}" --yes "prod.keystore.asc"

      - name: Run Fastlane Assemble Play Release Lane
        run: fastlane assemble_play_release

  assemble_gallery:
    name: Assemble Gallery
    runs-on: ubuntu-latest
    #    if: ${{ github.workflow_run.conclusion == 'success' }} && ${{ github.event_name == 'push' }} && (${{ github.ref_name == 'develop' }} || ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'release' }})

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Restore Prod Secrets
        run: |
          echo "prod_signing_key_alias=${{ secrets.PROD_SIGNING_KEY_ALIAS }}" >> secrets.properties
          echo "prod_signing_key_password=${{ secrets.PROD_SIGNING_KEY_PASSWORD }}" >> secrets.properties
          echo "prod_signing_keystore_password=${{ secrets.PROD_SIGNING_KEYSTORE_PASSWORD }}" >> secrets.properties
          echo "${{ secrets.PROD_KEYSTORE }}" > prod.keystore.asc
          gpg --batch --decrypt --output "config/keystore/prod.keystore" --passphrase "${{ secrets.PROD_SIGNING_KEYSTORE_GPG }}" --yes "prod.keystore.asc"

      - name: Run Fastlane Assemble Gallery Release Lane
        run: fastlane assemble_gallery_release

  assemble_foss:
    name: Assemble FOSS
    runs-on: ubuntu-latest
    #    if: ${{ github.workflow_run.conclusion == 'success' }} && ${{ github.event_name == 'push' }} && (${{ github.ref_name == 'develop' }} || ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'release' }})

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Restore Prod Secrets
        run: |
          echo "prod_signing_key_alias=${{ secrets.PROD_SIGNING_KEY_ALIAS }}" >> secrets.properties
          echo "prod_signing_key_password=${{ secrets.PROD_SIGNING_KEY_PASSWORD }}" >> secrets.properties
          echo "prod_signing_keystore_password=${{ secrets.PROD_SIGNING_KEYSTORE_PASSWORD }}" >> secrets.properties
          echo "${{ secrets.PROD_KEYSTORE }}" > prod.keystore.asc
          gpg --batch --decrypt --output "config/keystore/prod.keystore" --passphrase "${{ secrets.PROD_SIGNING_KEYSTORE_GPG }}" --yes "prod.keystore.asc"

      - name: Run Fastlane Assemble FOSS Release Lane
        run: fastlane assemble_foss_release