name: Upload data

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Run Fastlane Ktlint Lane
        run: fastlane ktlint
